
name: 'Build Example corne_choc_pro dvorak'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["corne_choc_pro_left","corne_choc_pro_right"]'
      alphas: '["dvorak"]'
      shield: '["nice_view"]'
